### ISSUE TITLE
feature request: add RJ45 and/or POE to the CapiBridge

### ISSUE THREAD

**Issue by steuerzentrale** [PricelessToolkit/CapiBridge#5]
Hi there

I use your superb mailbox-sensor and the LILYGO TTGO LoRa32 V2.1 1.6.1. My goal is to replace as many wireless components as possible as I have experienced Wifi-issues at my home.

Do you plan to offer CapiBridge with an RJ45 and/or POE-option? It would give the user the flexibility in terms of connectivity and would be a huge USP as there are almost no LoRa-gateways with RJ45 and/or POE on the market.

Best,
Andrew

**Comment by PricelessToolkit** [comment]
The concept is solid, and it was designed with expandability in mind. The only challenge is finding enough time to bring everything to completion. If time allows, I plan to launch it as an open-source project, enabling the community members to order assembled boards from  Chinese manufacturers.
