### ISSUE TITLE
Combine firmware ESP1 & ESP2

### ISSUE THREAD

**Issue by BoguslavskyiR** [PricelessToolkit/CapiBridge#7]
To make self-assembly easier and reduce the chance of errors when selecting the device, I propose using one of the free pins on both chips, such as IO7 as a MASK pin. For example:

- **For ESP1:** Connect pin IO7 to GND.
- **For ESP2:** Connect pin IO7 to 3.3V.

From the software side, in the setup section, you need to add a check for the state of this pin. If `digitalRead(MaskPin) == HIGH`, it corresponds to ESP2, else ESP1

**Comment by PricelessToolkit** [comment]
Hmm, nice idea!!👍 if in the future I have a project with an identical MCU I will implement that Thanks!!
